import { ProductDto } from "@/types";

export const GET = async () => {
    const mockProducts: ProductDto[] = [
        {
            description: "Tasty apple. Try it by your own.",
            image: "",
            name: "Apple",
            price: 200,
            id: 0,
        },
        {
            description: "Tasty apple. Try it by your own.",
            image: "",
            name: "Apple",
            price: 200,
            id: 0,
        },
        {
            description: "Tasty apple. Try it by your own.",
            image: "",
            name: "Apple",
            price: 200,
            id: 0,
        },
        {
            description: "Tasty apple. Try it by your own.",
            image: "",
            name: "Apple",
            price: 200,
            id: 0,
        },
        {
            description: "Tasty apple. Try it by your own.",
            image: "",
            name: "Apple",
            price: 200,
            id: 0,
        },
        {
            description: "Tasty apple. Try it by your own.",
            image: "",
            name: "Apple",
            price: 200,
            id: 0,
        },
        {
            description: "Tasty apple. Try it by your own.",
            image: "",
            name: "Apple",
            price: 200,
            id: 0,
        },
        {
            description: "Tasty apple. Try it by your own.",
            image: "",
            name: "Apple",
            price: 200,
            id: 0,
        },
        {
            description: "Tasty apple. Try it by your own.",
            image: "",
            name: "Apple",
            price: 200,
            id: 0,
        },
        {
            description: "Tasty apple. Try it by your own.",
            image: "",
            name: "Apple",
            price: 200,
            id: 0,
        },
        {
            description: "Tasty apple. Try it by your own.",
            image: "",
            name: "Apple",
            price: 200,
            id: 0,
        },
        {
            description: "Tasty apple. Try it by your own.",
            image: "",
            name: "Apple",
            price: 200,
            id: 0,
        },
        {
            description: "Tasty apple. Try it by your own.",
            image: "",
            name: "Apple",
            price: 200,
            id: 0,
        },
        {
            description: "Tasty apple. Try it by your own.",
            image: "",
            name: "Apple",
            price: 200,
            id: 0,
        },
        {
            description: "Tasty apple. Try it by your own.",
            image: "",
            name: "Apple",
            price: 200,
            id: 0,
        },
        {
            description: "Tasty apple. Try it by your own.",
            image: "",
            name: "Apple",
            price: 200,
            id: 0,
        },
        {
            description: "Tasty apple. Try it by your own.",
            image: "",
            name: "Apple",
            price: 200,
            id: 0,
        },
        {
            description: "Tasty apple. Try it by your own.",
            image: "",
            name: "Apple",
            price: 200,
            id: 0,
        },
        {
            description: "Tasty apple. Try it by your own.",
            image: "",
            name: "Apple",
            price: 200,
            id: 0,
        },
        {
            description: "Tasty apple. Try it by your own.",
            image: "",
            name: "Apple",
            price: 200,
            id: 0,
        },
        {
            description: "Tasty apple. Try it by your own.",
            image: "",
            name: "Apple",
            price: 200,
            id: 0,
        },
        {
            description: "Tasty apple. Try it by your own.",
            image: "",
            name: "Apple",
            price: 200,
            id: 0,
        },
        {
            description: "Tasty apple. Try it by your own.",
            image: "",
            name: "Apple",
            price: 200,
            id: 0,
        },
        {
            description: "Tasty apple. Try it by your own.",
            image: "",
            name: "Apple",
            price: 200,
            id: 0,
        },
        {
            description: "Tasty apple. Try it by your own.",
            image: "",
            name: "Apple",
            price: 200,
            id: 0,
        },
        {
            description: "Tasty apple. Try it by your own.",
            image: "",
            name: "Apple",
            price: 200,
            id: 0,
        },
        {
            description: "Tasty apple. Try it by your own.",
            image: "",
            name: "Apple",
            price: 200,
            id: 0,
        },
        {
            description: "Tasty apple. Try it by your own.",
            image: "",
            name: "Apple",
            price: 200,
            id: 0,
        },
        {
            description: "Tasty apple. Try it by your own.",
            image: "",
            name: "Apple",
            price: 200,
            id: 0,
        },
    ];

    return Response.json(mockProducts);
};
